---
title: "cryptid_maps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(leaflet)
library(RColorBrewer)
library(shiny)
```

Test map (bigfoot subset)
```{r}
bigfoot_subset_popup <-paste("weather:", bigfoot_subset$season,
                      "</br>", "date:", bigfoot_subset$date,
                      "</br>", "summary:", bigfoot_subset$title)

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(lng = ~longitude, lat = ~latitude, 
                   data = bigfoot_subset, radius = 5, 
                   stroke = FALSE, fillOpacity = 0.5, 
                   popup = bigfoot_subset_popup
                   )
```

test map (bigfoot full?)
```{r}
bigfoot_popup <-paste("season:", bigfoot$season,
                      "</br>", "date:", bigfoot$date,
                      "</br>", "summary:", bigfoot$title)

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(lng = ~longitude, lat = ~latitude, 
                   data = bigfoot, radius = 5, 
                   stroke = FALSE, fillOpacity = 0.5, 
                   popup = bigfoot_popup
                   )
```
test map (ufo 1 full?)
```{r}
ufo_popup <-paste("shape:", ufo$shape,
                      "</br>", "date:", ufo$date_time)

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(lng = ~city_longitude, lat = ~city_latitude, 
                   data = ufo, radius = 5, 
                   stroke = FALSE, fillOpacity = 0.5, 
                   popup = ufo_popup
                   )
```

test map(dogman full?)
```{r}
dogman_popup <-paste("date:", dogman$date,
                      "</br>", "desc:", dogman$description)

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(lng = ~longitude, lat = ~latitude, 
                   data = dogman, radius = 5, 
                   stroke = FALSE, fillOpacity = 0.5, 
                   popup = dogman_popup
                   )
```

```{r}
# bigfoot_sep <- bigfoot %>%
#   separate(date, sep = "-", into = c("year", "month", "day")) %>%
#   mutate(year = as.numeric(year), na.rm = TRUE)

bigfoot_sep <- bigfoot %>%
  mutate(date = as.Date(date))
  
```

shiny test
```{r}
ui <- fluidPage(
  
  p(),
  sidebarLayout(
    sidebarPanel(checkboxGroupInput(inputId = "season",
                                choices = unique(bigfoot_sep$season),
                                selected = unique(bigfoot_sep$season),
                                label = "select season"), 
                 dateRangeInput(inputId = "date", 
                                start = "1900-01-01",
                                end = "2022-01-01",
                             min = "1900-01-01", 
                             max = "2022-01-01", 
                             label = "select date range")),
  mainPanel(leafletOutput("mymap"))))

server <- function(input, output, session) {

  points <- reactive({
    bigfoot_sep %>%
    filter(season %in% input$season, na.rm = TRUE) %>%
    filter(date <= input$date[2], date >= input$date[1])
  
})
  

  

    output$mymap <- renderLeaflet({
          content <- 
    paste("season:", points()$season,
                      "</br>", "date:", points()$date,
                      "</br>", "summary:", points()$title)

    leaflet() %>%
      addTiles() %>%
      addCircleMarkers(radius = 5, 
                   stroke = FALSE, fillOpacity = 0.5, 
                   data = points(), popup = content)
  })
}

shinyApp(ui, server)
```

