---
title: "fish"
author: "Grisha Post"
date: "5/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse, leaflet, RColorBrewer, ggthemes, spatstat, raster, maptools)
```

```{r}
bigfoot <- read.csv("bfro_reports_geocoded.csv")
bigfoot_subset <- bigfoot %>% 
  slice_sample(n = 200)
```

```{r}
#Filter out Alaska and error water points. 
bigfoottrim2 <- bigfoot %>%
  filter(state != "Alaska") %>%
  filter(number != "38287") %>%
  filter(number != "36759") %>%
  filter(number != "17240") 
  
#Trim more
bigfoottrim3 <- bigfoottrim2 %>%
  dplyr::select(latitude, longitude) %>%
  rename(lat = latitude, long = longitude) %>%
  relocate(long, lat) %>%
  drop_na()

```

```{r}
visual <- ggplot(data = bigfoottrim3,
mapping = aes(x = long, y = lat)) +
geom_point() +
ggtitle('Thicc Foot') +
theme_wsj()

visual
```

```{r}
mypattern <- ppp(bigfoottrim3[,1], bigfoottrim3[,2], c(-135, -66), c(23, 50))
k <- Kest(mypattern)
plot(k)
```

```{r}
r <- raster(ncol = 20, nrow = 20,
            xmn = -135, xmx = -66,
            ymn = 23, ymx = 50)

raster <- rasterize(bigfoottrim3, r, fun = "count")
plot(raster)
```

```{r}
us <- raster::getData('GADM', country = 'USA', level= 0 ) #Get the County Shapefile for the US
us_crop <- raster::crop(us, extent(-135, -66, 23, 50))
plot(us_crop)
```

```{r}
proj4string(us_crop) <- ""
usowin <- as.owin(us_crop)

p <- ppp(bigfoottrim3[,1], bigfoottrim3[,2], window = usowin)
plot(p)
```

```{r}
ds <- density(p)
plot(ds, main = "Bigfoot Sightings")
```